export enum WebSocketEnum {
	// От клиента
	AUTH = "AUTH",
	CREATE_OR_GET_CHAT = "CREATE_OR_GET_CHAT",
	SEND_MESSAGE = "SEND_MESSAGE",
	GET_CHATS = "GET_CHATS",
	GET_CHAT_HISTORY = "GET_CHAT_HISTORY",
	SEARCH_USERS = "SEARCH_USERS",
	SUBSCRIBE_TO_CHAT = "SUBSCRIBE_TO_CHAT",
	UNSUBSCRIBE_FROM_CHAT = "UNSUBSCRIBE_FROM_CHAT",
	CHAT_CREATED = "CHAT_CREATED",

	// От сервера
	CHAT_READY = "CHAT_READY",
	MESSAGE_CREATED = "MESSAGE_CREATED",
	CHATS_LIST = "CHATS_LIST",
	CHAT_HISTORY = "CHAT_HISTORY",
	USERS_SEARCH_RESULT = "USERS_SEARCH_RESULT",
	INVALIDATE = "INVALIDATE",
	ERROR = "ERROR",
}
